// <auto-generated />
using Company.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Company.Data.Migrations
{
    [DbContext(typeof(WoningContext))]
    partial class WoningContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Company.Data.Bewoner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WoningId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WoningId");

                    b.ToTable("Bewoners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Joosten",
                            WoningId = 2
                        },
                        new
                        {
                            Id = 2,
                            Naam = "Verschoor",
                            WoningId = 2
                        },
                        new
                        {
                            Id = 3,
                            Naam = "Rubens",
                            WoningId = 3
                        },
                        new
                        {
                            Id = 4,
                            Naam = "Van Zanten",
                            WoningId = 3
                        });
                });

            modelBuilder.Entity("Company.Data.Woning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Huisnummer")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Woningen");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Huisnummer = 0,
                            Naam = "zelftevree"
                        },
                        new
                        {
                            Id = 3,
                            Huisnummer = 0,
                            Naam = "boslust"
                        });
                });

            modelBuilder.Entity("Company.Data.Bewoner", b =>
                {
                    b.HasOne("Company.Data.Woning", "Woning")
                        .WithMany("Bewoners")
                        .HasForeignKey("WoningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
